 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', us-central1-docker.pkg.dev/capstone-project-375618/dockerwebsite:$COMMIT_SHA', '.']
serviceAccount: 'projects/capstone-project-375618/serviceAccounts/website@capstone-project-375618.iam.gserviceaccount.com'
 # Push the container image to Artifact Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', us-central1-docker.pkg.dev/capstone-project-375618/dockerwebsite:$COMMIT_SHA']
serviceAccount: 'projects/capstone-project-375618/serviceAccounts/website@capstone-project-375618.iam.gserviceaccount.com'
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'website'
   - '--image'
   - us-central1-docker.pkg.dev/capstone-project-375618/dockerwebsite:$COMMIT_SHA'
   - '--region'
   - 'us-central1'
  images:
  - us-central1-docker.pkg.dev/capstone-project-375618/dockerwebsite:$COMMIT_SHA'
serviceAccount: 'projects/capstone-project-375618/serviceAccounts/website@capstone-project-375618.iam.gserviceaccount.com'

  
