 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'us-central1-docker.pkg.dev/capstone-project-375618/docker/website:$COMMIT_SHA', '.']
 # Push the container image to Artifact Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'us-central1-docker.pkg.dev/capstone-project-375618/docker/website:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'website'
   - '--image=us-central1-docker.pkg.dev/capstone-project-375618/docker/website:$COMMIT_SHA'
   - '--region=us-central1'
   - '--service-account=website@capstone-project-375618.iam.gserviceaccount.com'
limits:
  - 'containerConcurrency: 10"
  - 'cpu 1'
  - 'memory: 512Mi'
images:
- 'us-central1-docker.pkg.dev/capstone-project-375618/docker/website:$COMMIT_SHA'
options:
  logging: NONE 


  
