 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'us.gcr.io/capstone-project-375618/website:$COMMIT_SHA', '.']
  options:
  logging: NONE 
 # Push the container image to Artifact Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'us.gcr.io/capstone-project-375618/website:$COMMIT_SHA']
  options:
  logging: NONE
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'website'
   - '--image'
   - 'us.gcr.io/capstone-project-375618/website:$COMMIT_SHA'
   - '--region'
   - 'us-central1'
  images:
  - 'us.gcr.io/capstone-project-375618/website:$COMMIT_SHA'
  options:
  logging: NONE 
